import "../styles/globals.css";
import { Nunito_Sans } from "next/font/google";
import Header from "../Components/Header";
import Footer from "@/Components/Footer";
import { Providers } from "@/redux/provider";

const nunito = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` min-h-screen ${nunito.className}`}>
        <Providers>
          <Header></Header>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
